"""Phase 1 to Phase 2 handover: opening a technical review on a saved record.

The business intake and the technical review are two interviews over **one**
record. Phase 1 fills `business`, `sizing` and the shallow half of `technical`;
Phase 2 fills `technical.network`, `.security`, `.grounding` and the systems
matrix. They are separate conversations, usually held by different people days
apart, so the only thing tying them together is the record id.

That makes the store the seam. `RecordStore.load_record` reads a record written
by any earlier session, and this module turns one into a fresh `tech` session.

**This only works when the store is durable.** `create_default_store()` falls
back to `InMemorySessionStore` when neither `QUALIFY_GCS_BUCKET` nor
`QUALIFY_DATA_DIR` is set, and an in-memory store has no record to find — the
Phase 1 conversation lived in a process that has since been replaced. The
caller gets a clear `HandoverError` rather than an empty review, because an
empty review that looks like it worked is the failure mode that wrote an
`Untitled Initiative` folder to SharePoint last time.
"""

from __future__ import annotations

import logging
import re

from qualify.schema.use_case_record import UseCaseRecord
from qualify.sinks.record_store import RecordStore
from qualify.sinks.session import Session, SessionStore

log = logging.getLogger(__name__)

#: The pack a handover opens. Named here so the string appears once.
TECH_PACK = "tech"

#: How many pending opportunities to offer at once.
#:
#: A chat reply is not a data grid. Past roughly this many the list stops being
#: something a reviewer reads and starts being something they scroll, and the
#: right answer becomes a search rather than a longer list.
PENDING_REVIEW_LIMIT = 10

#: `UC-2026-A1B2C3`. Generated by `new_session` from the context id, so the
#: suffix is whatever survived stripping hyphens and upper-casing — letters and
#: digits, length not guaranteed. Kept loose on purpose: a reviewer pasting an
#: id from a SharePoint folder name should not fail on a length check.
RECORD_ID_RE = re.compile(r"\bUC-\d{4}-[A-Z0-9]+\b", re.IGNORECASE)

#: Phrases that mean "start the technical review".
#:
#: Matched as substrings against the lower-cased message. Deliberately narrow:
#: every one of these names the review explicitly, so ordinary conversation
#: about technical topics cannot trip it.
_TRIGGERS = (
    "technical review",
    "tech review",
    "technical architecture review",
    "architecture review",
    "start phase 2",
    "phase 2 review",
    "pending documents to review",
    "pending opportunities to review",
    "documents to review",
    "opportunities to review",
    "pending review",
    "pending reviews",
    "pending opportunities",
    "show me pending",
    "list pending",
    "what is pending",
)


class HandoverError(Exception):
    """Raised when a technical review cannot be opened.

    Carries a message written for the user, not for the log, because every
    failure here is something they can act on: fix the id, finish Phase 1, or
    tell an engineer the store is not configured.
    """


def parse_tech_review_intent(user_text: str | None) -> tuple[bool, str | None]:
    """Reads a "start the technical review" request out of a chat message.

    Returns `(wants_review, record_id)`. The two are separate because
    "start the technical review" without an id is a real request that deserves
    a helpful reply, not silence — the user knows what they want and has simply
    not said which initiative.
    """
    if not user_text:
        return False, None

    text = user_text.strip()
    lowered = text.lower()

    wants = any(t in lowered for t in _TRIGGERS)
    if not wants:
        return False, None

    match = RECORD_ID_RE.search(text)
    return True, match.group(0).upper() if match else None


_CHOICE_PREFIXES = (
    "let's start a tech review for",
    "lets start a tech review for",
    "let's start a technical review for",
    "lets start a technical review for",
    "start a technical review for",
    "start a tech review for",
    "start technical review for",
    "start tech review for",
    "let's start with",
    "lets start with",
    "start with",
    "let's review",
    "lets review",
    "technical review for",
    "technical review",
    "tech review for",
    "tech review",
    "architecture review for",
    "architecture review",
    "start phase 2 for",
    "start phase 2",
    "phase 2 review for",
    "phase 2 review",
    "let's do",
    "lets do",
    "review",
    "open",
    "select",
    "choose",
    "option",
    "number",
    "num",
    "for",
    "the",
)

_ORDINAL_WORDS = {
    "first": 1,
    "1st": 1,
    "second": 2,
    "2nd": 2,
    "third": 3,
    "3rd": 3,
    "fourth": 4,
    "4th": 4,
    "fifth": 5,
    "5th": 5,
}


def resolve_pending_review_choice(
    user_text: str | None, choices: list[dict]
) -> str | None:
    """Resolves a user's selection against a list of pending review opportunities.

    Supports:
    - Explicit record ID: `UC-2026-0CD0BC` or `let's do UC-2026-0CD0BC`
    - 1-based index/number: `1`, `#1`, `option 1`, `the first one`
    - Initiative name/title: `AAA`, `let's start with AAA`, `AP Invoice Exception Assistant`
    """
    if not user_text or not choices:
        return None

    text = user_text.strip()
    if not text:
        return None

    # 1. Explicit UC-XXXX-XXXXXX record ID anywhere in the message
    id_match = RECORD_ID_RE.search(text)
    if id_match:
        return id_match.group(0).upper()

    lowered = text.lower().strip(" .!?'\"")

    # 2. Strip conversational prefixes first so both numeric/ordinal ("let's start with 1",
    # "let's do the first one") and title ("let's start with AAA") inputs are normalized.
    cleaned = lowered
    changed = True
    while changed:
        changed = False
        for prefix in _CHOICE_PREFIXES:
            if cleaned.startswith(prefix + " "):
                cleaned = cleaned[len(prefix) :].strip(" .!?'\"-")
                changed = True
            elif cleaned == prefix:
                cleaned = ""
                changed = True

    for candidate in (lowered, cleaned):
        if not candidate:
            continue
        # Numeric index (e.g. "1", "#1", "option 1", "number 2", "rank 1")
        num_match = re.fullmatch(
            r"(?:option|number|num|rank|item|#)?\s*(\d+)(?:\s*one)?", candidate
        )
        if num_match:
            idx = int(num_match.group(1))
            if 1 <= idx <= len(choices):
                return choices[idx - 1].get("recordId")

        # Ordinal words (e.g. "first", "the first one", "let's start with the first one")
        for word, idx in _ORDINAL_WORDS.items():
            if re.fullmatch(rf"(?:the\s+)?{word}(?:\s+one)?", candidate):
                if 1 <= idx <= len(choices):
                    return choices[idx - 1].get("recordId")

    if not cleaned:
        return None

    # 3a. Exact case-insensitive title match against cleaned text or full text
    for item in choices:
        name = (item.get("initiativeName") or item.get("name") or "").strip()
        if not name:
            continue
        if name.lower() == cleaned or name.lower() == lowered:
            return item.get("recordId")

    # 3b. Substring match (sort by name length descending so specific multi-word
    # names like "AP Invoice Exception Assistant" match before short names like "a")
    sorted_choices = sorted(
        choices,
        key=lambda c: len((c.get("initiativeName") or c.get("name") or "").strip()),
        reverse=True,
    )
    for item in sorted_choices:
        name = (item.get("initiativeName") or item.get("name") or "").strip()
        if not name:
            continue
        name_low = name.lower()
        if len(name_low) >= 2 and re.search(rf"\b{re.escape(name_low)}\b", lowered):
            return item.get("recordId")
        if len(cleaned) >= 3 and cleaned in name_low:
            return item.get("recordId")

    return None



def load_review_record(
    store: SessionStore, record_id: str, context_id: str | None = None
) -> UseCaseRecord | None:
    """Finds a record by id, preferring the store and falling back to SharePoint.

    Two sources, in that order, because they fail in opposite directions. The
    store is fast, needs no user token and holds the freshest copy — but only
    for records written by a store-backed revision of this service. SharePoint
    is slower and needs the reviewer to be signed in, but it is where the
    artefacts actually live, and it survives deploys, store migrations and the
    in-memory fallback that produced the records we cannot otherwise reach.

    The SharePoint copy is a snapshot from the last sync, so it can lag a
    business interview still in progress. That is the same thing a human sees
    in the folder, which makes it the honest answer rather than a stale one.
    """
    if isinstance(store, RecordStore):
        record = store.load_record(record_id)
        if record is not None:
            log.info("Handover: record %s came from the record store", record_id)
            return record

    try:
        from qualify.connectors.sharepoint import (  # noqa: PLC0415
            get_sharepoint_connector,
        )

        record = get_sharepoint_connector().load_opportunity(
            record_id, delegated_token=None, context_id=context_id
        )
    except Exception as exc:
        # A SharePoint outage must not turn into a stack trace in the chat.
        # The caller reports "not found", which is what the reviewer can act on.
        log.warning("Handover: SharePoint lookup for %s failed: %s", record_id, exc)
        return None

    if record is not None:
        log.info("Handover: record %s came from SharePoint", record_id)
    return record


def start_tech_review(
    store: SessionStore, context_id: str, record_id: str
) -> Session:
    """Opens a technical review against an existing business record.

    The new session shares the record object wholesale rather than copying
    selected fields across. Phase 2 is a continuation of the same use case, so
    the initiative name, the problem statement and the sizing all stay
    authoritative and visible; the tech pack renders them readonly.

    Raises:
        HandoverError: neither the store nor SharePoint holds the record.
    """
    record = load_review_record(store, record_id, context_id)
    if record is None:
        raise HandoverError(_not_found_message(store, record_id))

    log.info(
        "Handover: opening tech review context_id=%s record_id=%s",
        context_id,
        record_id,
    )

    # Populate indicative capability level when Phase 1 recorded inputs (data sources,
    # user stories, or problem statement) but capability_level was not yet persisted.
    has_phase1_inputs = bool(
        record.technical.data_sources
        or record.technical.other_data_sources
        or record.business.user_stories
        or record.business.problem_description
    )
    if record.technical.capability_level is None and has_phase1_inputs:
        from qualify.scoring.business_tier import classify_capability  # noqa: PLC0415

        classify_capability(record)

    session = Session(
        context_id=context_id,
        pack_name=TECH_PACK,
        record=record,
    )
    store.save(session)
    return session


def _not_found_message(store: SessionStore, record_id: str) -> str:
    """Explains a failed lookup in terms of what the reader can do next.

    A deployment with no durable store fails for a different reason than a
    mistyped id, and the two need different advice. Collapsing them into one
    message sends a reviewer hunting for a typo in a correct id.
    """
    if not isinstance(store, RecordStore):
        return (
            f"I can't find record **{record_id}**.\n\n"
            "This deployment has no durable record store, so the only place "
            "left to look was SharePoint, and it isn't there either. If the "
            "business intake was completed, ask an engineer to set "
            "`QUALIFY_GCS_BUCKET` on the service — without it, records from "
            "earlier conversations are unreachable."
        )
    return (
        f"I can't find record **{record_id}** in the record store or in "
        f"SharePoint. Check the id — it appears at the top of the Business "
        f"Value Brief and in the SharePoint folder name. The business intake "
        f"also has to have been saved before a technical review can start."
    )


_SOURCE_LABELS: dict[str, str] = {
    "google_drive": "Google Drive / Docs",
    "gmail_calendar": "Gmail & Google Calendar",
    "sharepoint": "Microsoft SharePoint",
    "sharepoint_onedrive": "Microsoft SharePoint / OneDrive",
    "confluence": "Atlassian Confluence",
    "jira": "Atlassian Jira",
    "salesforce": "Salesforce CRM",
    "servicenow": "ServiceNow",
    "bigquery": "Google BigQuery",
    "cloud_sql": "Google Cloud SQL / AlloyDB",
    "sap_erp": "SAP ERP",
    "workday": "Workday",
    "zendesk": "Zendesk",
    "slack_teams": "Slack / Microsoft Teams",
    "public_web": "Public Web Grounding",
}


def format_source_names(sources: list[str], other: str | None = None) -> str:
    """Formats Phase 1 data source slugs into human-readable display names."""
    items = [
        _SOURCE_LABELS.get(s, s.replace("_", " ").title())
        for s in sources
        if s != "other"
    ]
    if other:
        items.append(other)
    return ", ".join(items)


def baseline_summary(session: Session) -> str:
    """A structured Opportunity Brief recapping what Phase 1 established.

    Shown on the handover turn so the Solution Architect immediately understands
    the business problem, target persona, estimated ROI, systems in scope, and
    recommended Gemini Enterprise capability tier before starting Stage 1.
    """
    record = session.record
    name = record.meta.initiative_name or "Unnamed initiative"
    lines = [f"#### 📋 Opportunity Summary — **{name}** (`{record.meta.record_id}`)"]

    if record.business.problem_description:
        lines.append(f"- **Problem Statement:** {record.business.problem_description}")
    if record.business.user_stories:
        lines.append(f"- **Target Workflow / User Stories:** {record.business.user_stories}")
    if record.business.expected_impacts:
        lines.append(
            f"- **Expected Business Impacts:** {', '.join(record.business.expected_impacts)}"
        )

    if record.meta.department_bu:
        owner_suffix = (
            f" (Business Owner: {record.proposed.business_owner})"
            if record.proposed.business_owner
            else ""
        )
        lines.append(f"- **Team:** {record.meta.department_bu}{owner_suffix}")

    if record.business.user_count is not None:
        persona = f" ({record.business.user_profile})" if record.business.user_profile else ""
        hours = record.derived.total_annual_team_hours_saved
        hours_suffix = (
            f" · **{hours:,.0f} hrs/yr** estimated savings"
            if hours is not None
            else ""
        )
        lines.append(
            f"- **Affected users:** {record.business.user_count}{persona}{hours_suffix}"
        )

    if record.technical.data_sources or record.technical.other_data_sources:
        pretty_sources = format_source_names(
            record.technical.data_sources, record.technical.other_data_sources
        )
        lines.append(f"- **Systems named in Phase 1:** {pretty_sources}")

    if record.technical.capability_level is not None:
        from qualify.scoring.business_tier import classify_capability  # noqa: PLC0415

        classify_capability(record)
        tier = record.technical.capability_level.delivery_tier
        cap_label = record.technical.capability_level.label
        lines.append(
            f"- **Indicative delivery tier:** **{tier.label}** — *{cap_label}*"
        )
        lines.append(
            f"- **Architect Review Focus:** {_architect_review_focus(record)}"
        )

    return "\n".join(lines)


def _architect_review_focus(record: UseCaseRecord) -> str:
    """One-line architectural focus for the Solution Architect in Phase 2."""
    from qualify.schema.capability import CapabilityLevel  # noqa: PLC0415

    lvl = record.technical.capability_level
    sources = format_source_names(
        record.technical.data_sources, record.technical.other_data_sources
    ) or "the target repositories"

    if lvl in (
        CapabilityLevel.WORKFLOW_AGENT_WITH_CUSTOM_MCP,
        CapabilityLevel.HIGH_CODE_AGENT,
    ):
        return (
            f"Delegated to **Pro-Code ({lvl.label})** — verify API schemas, "
            f"Workload Identity / OAuth 2.0 auth, VPC network transit, and "
            f"whether to deploy on **Vertex AI Agent Runtime (ADK)** or **Cloud Run (A2A/MCP)** for {sources}."
        )
    if lvl in (
        CapabilityLevel.WORKFLOW_BUILDER_CHAT_AGENT,
        CapabilityLevel.WORKFLOW_BUILDER_WORKFLOW_AGENT,
    ):
        return (
            f"Scoped for **Low-Code ({lvl.label})** over {sources} — confirm whether "
            f"native Gemini Enterprise connectors cover all required queries/actions "
            f"(read-only vs. write) and preserve document-level ACLs, or if custom APIs require **Pro-Code (Level 5/6)**."
        )
    return (
        "Scoped for **No-Code (Gemini Enterprise Assistant / Custom Skill)** — "
        "confirm no live backend system connectors or automated writes are required."
    )


def list_pending_reviews(
    context_id: str | None = None, limit: int = PENDING_REVIEW_LIMIT
) -> tuple[list[dict], bool]:
    """Opportunities in SharePoint that hold a brief and no dossier.

    Returns `(pending, reachable)`. The flag is the point: an empty list means
    "everything is reviewed", while an unreachable SharePoint means "I don't
    know", and a reviewer told the first when the second is true will conclude
    there is no work and stop. Only the connector can tell them apart, so the
    distinction has to survive the return.

    Entries without a parsable record id are dropped. They are real folders and
    the listing will still show them, but they cannot be offered as a review
    target when we cannot say which record they are.
    """
    try:
        from qualify.connectors.sharepoint import (  # noqa: PLC0415
            get_sharepoint_connector,
        )

        entries = get_sharepoint_connector().list_opportunities(
            context_id=context_id,
            pending_technical_review=True,
            limit=limit,
        )
    except Exception as exc:
        log.warning("Handover: could not list pending reviews: %s", exc)
        return [], False

    return [e for e in entries if e.get("recordId")], True
