"""Phase 1 to Phase 2 handover: opening a technical review on a saved record.

The business intake and the technical review are two interviews over **one**
record. Phase 1 fills `business`, `sizing` and the shallow half of `technical`;
Phase 2 fills `technical.network`, `.security`, `.grounding` and the systems
matrix. They are separate conversations, usually held by different people days
apart, so the only thing tying them together is the record id.

That makes the store the seam. `RecordStore.load_record` reads a record written
by any earlier session, and this module turns one into a fresh `tech` session.

**This only works when the store is durable.** `create_default_store()` falls
back to `InMemorySessionStore` when neither `QUALIFY_GCS_BUCKET` nor
`QUALIFY_DATA_DIR` is set, and an in-memory store has no record to find — the
Phase 1 conversation lived in a process that has since been replaced. The
caller gets a clear `HandoverError` rather than an empty review, because an
empty review that looks like it worked is the failure mode that wrote an
`Untitled Initiative` folder to SharePoint last time.
"""

from __future__ import annotations

import logging
import re

from qualify.schema.use_case_record import UseCaseRecord
from qualify.sinks.record_store import RecordStore
from qualify.sinks.session import Session, SessionStore

log = logging.getLogger(__name__)

#: The pack a handover opens. Named here so the string appears once.
TECH_PACK = "tech"

#: How many pending opportunities to offer at once.
#:
#: A chat reply is not a data grid. Past roughly this many the list stops being
#: something a reviewer reads and starts being something they scroll, and the
#: right answer becomes a search rather than a longer list.
PENDING_REVIEW_LIMIT = 10

#: `UC-2026-A1B2C3`. Generated by `new_session` from the context id, so the
#: suffix is whatever survived stripping hyphens and upper-casing — letters and
#: digits, length not guaranteed. Kept loose on purpose: a reviewer pasting an
#: id from a SharePoint folder name should not fail on a length check.
RECORD_ID_RE = re.compile(r"\bUC-\d{4}-[A-Z0-9]+\b", re.IGNORECASE)

#: Phrases that mean "start the technical review".
#:
#: Matched as substrings against the lower-cased message. Deliberately narrow:
#: every one of these names the review explicitly, so ordinary conversation
#: about technical topics cannot trip it.
_TRIGGERS = (
    "technical review",
    "tech review",
    "technical architecture review",
    "architecture review",
    "start phase 2",
    "phase 2 review",
)


class HandoverError(Exception):
    """Raised when a technical review cannot be opened.

    Carries a message written for the user, not for the log, because every
    failure here is something they can act on: fix the id, finish Phase 1, or
    tell an engineer the store is not configured.
    """


def parse_tech_review_intent(user_text: str | None) -> tuple[bool, str | None]:
    """Reads a "start the technical review" request out of a chat message.

    Returns `(wants_review, record_id)`. The two are separate because
    "start the technical review" without an id is a real request that deserves
    a helpful reply, not silence — the user knows what they want and has simply
    not said which initiative.
    """
    if not user_text:
        return False, None

    text = user_text.strip()
    lowered = text.lower()

    wants = any(t in lowered for t in _TRIGGERS)
    if not wants:
        return False, None

    match = RECORD_ID_RE.search(text)
    return True, match.group(0).upper() if match else None


def load_review_record(
    store: SessionStore, record_id: str, context_id: str | None = None
) -> UseCaseRecord | None:
    """Finds a record by id, preferring the store and falling back to SharePoint.

    Two sources, in that order, because they fail in opposite directions. The
    store is fast, needs no user token and holds the freshest copy — but only
    for records written by a store-backed revision of this service. SharePoint
    is slower and needs the reviewer to be signed in, but it is where the
    artefacts actually live, and it survives deploys, store migrations and the
    in-memory fallback that produced the records we cannot otherwise reach.

    The SharePoint copy is a snapshot from the last sync, so it can lag a
    business interview still in progress. That is the same thing a human sees
    in the folder, which makes it the honest answer rather than a stale one.
    """
    if isinstance(store, RecordStore):
        record = store.load_record(record_id)
        if record is not None:
            log.info("Handover: record %s came from the record store", record_id)
            return record

    try:
        from qualify.connectors.sharepoint import (  # noqa: PLC0415
            get_sharepoint_connector,
        )

        record = get_sharepoint_connector().load_opportunity(
            record_id, delegated_token=None
        )
    except Exception as exc:
        # A SharePoint outage must not turn into a stack trace in the chat.
        # The caller reports "not found", which is what the reviewer can act on.
        log.warning("Handover: SharePoint lookup for %s failed: %s", record_id, exc)
        return None

    if record is not None:
        log.info("Handover: record %s came from SharePoint", record_id)
    return record


def start_tech_review(
    store: SessionStore, context_id: str, record_id: str
) -> Session:
    """Opens a technical review against an existing business record.

    The new session shares the record object wholesale rather than copying
    selected fields across. Phase 2 is a continuation of the same use case, so
    the initiative name, the problem statement and the sizing all stay
    authoritative and visible; the tech pack renders them readonly.

    Raises:
        HandoverError: neither the store nor SharePoint holds the record.
    """
    record = load_review_record(store, record_id, context_id)
    if record is None:
        raise HandoverError(_not_found_message(store, record_id))

    log.info(
        "Handover: opening tech review context_id=%s record_id=%s",
        context_id,
        record_id,
    )

    session = Session(
        context_id=context_id,
        pack_name=TECH_PACK,
        record=record,
    )
    store.save(session)
    return session


def _not_found_message(store: SessionStore, record_id: str) -> str:
    """Explains a failed lookup in terms of what the reader can do next.

    A deployment with no durable store fails for a different reason than a
    mistyped id, and the two need different advice. Collapsing them into one
    message sends a reviewer hunting for a typo in a correct id.
    """
    if not isinstance(store, RecordStore):
        return (
            f"I can't find record **{record_id}**.\n\n"
            "This deployment has no durable record store, so the only place "
            "left to look was SharePoint, and it isn't there either. If the "
            "business intake was completed, ask an engineer to set "
            "`QUALIFY_GCS_BUCKET` on the service — without it, records from "
            "earlier conversations are unreachable."
        )
    return (
        f"I can't find record **{record_id}** in the record store or in "
        f"SharePoint. Check the id — it appears at the top of the Business "
        f"Value Brief and in the SharePoint folder name. The business intake "
        f"also has to have been saved before a technical review can start."
    )


def baseline_summary(session: Session) -> str:
    """A short prose recap of what Phase 1 established.

    Shown on the handover turn so the reviewer can see immediately whether they
    have the right initiative, before answering five stages of questions about
    the wrong one.
    """
    record = session.record
    name = record.meta.initiative_name or "Unnamed initiative"
    lines = [f"**{name}** (`{record.meta.record_id}`)"]

    if record.meta.department_bu:
        lines.append(f"- Team: {record.meta.department_bu}")
    if record.business.user_count is not None:
        lines.append(f"- Affected users: {record.business.user_count}")
    if record.technical.data_sources:
        lines.append(
            f"- Systems named in Phase 1: {', '.join(record.technical.data_sources)}"
        )
    if record.technical.capability_level is not None:
        tier = record.technical.capability_level.delivery_tier
        lines.append(f"- Indicative delivery tier: {tier.label}")

    return "\n".join(lines)


def list_pending_reviews(
    context_id: str | None = None, limit: int = PENDING_REVIEW_LIMIT
) -> tuple[list[dict], bool]:
    """Opportunities in SharePoint that hold a brief and no dossier.

    Returns `(pending, reachable)`. The flag is the point: an empty list means
    "everything is reviewed", while an unreachable SharePoint means "I don't
    know", and a reviewer told the first when the second is true will conclude
    there is no work and stop. Only the connector can tell them apart, so the
    distinction has to survive the return.

    Entries without a parsable record id are dropped. They are real folders and
    the listing will still show them, but they cannot be offered as a review
    target when we cannot say which record they are.
    """
    try:
        from qualify.connectors.sharepoint import (  # noqa: PLC0415
            get_sharepoint_connector,
        )

        entries = get_sharepoint_connector().list_opportunities(
            context_id=context_id,
            pending_technical_review=True,
            limit=limit,
        )
    except Exception as exc:
        log.warning("Handover: could not list pending reviews: %s", exc)
        return [], False

    return [e for e in entries if e.get("recordId")], True
