"""Phase 1 to Phase 2 handover: opening a technical review on a saved record.

The business intake and the technical review are two interviews over **one**
record. Phase 1 fills `business`, `sizing` and the shallow half of `technical`;
Phase 2 fills `technical.network`, `.security`, `.grounding` and the systems
matrix. They are separate conversations, usually held by different people days
apart, so the only thing tying them together is the record id.

That makes the store the seam. `RecordStore.load_record` reads a record written
by any earlier session, and this module turns one into a fresh `tech` session.

**This only works when the store is durable.** `create_default_store()` falls
back to `InMemorySessionStore` when neither `QUALIFY_GCS_BUCKET` nor
`QUALIFY_DATA_DIR` is set, and an in-memory store has no record to find — the
Phase 1 conversation lived in a process that has since been replaced. The
caller gets a clear `HandoverError` rather than an empty review, because an
empty review that looks like it worked is the failure mode that wrote an
`Untitled Initiative` folder to SharePoint last time.
"""

from __future__ import annotations

import logging
import re

from qualify.sinks.record_store import RecordStore
from qualify.sinks.session import Session, SessionStore

log = logging.getLogger(__name__)

#: The pack a handover opens. Named here so the string appears once.
TECH_PACK = "tech"

#: `UC-2026-A1B2C3`. Generated by `new_session` from the context id, so the
#: suffix is whatever survived stripping hyphens and upper-casing — letters and
#: digits, length not guaranteed. Kept loose on purpose: a reviewer pasting an
#: id from a SharePoint folder name should not fail on a length check.
RECORD_ID_RE = re.compile(r"\bUC-\d{4}-[A-Z0-9]+\b", re.IGNORECASE)

#: Phrases that mean "start the technical review".
#:
#: Matched as substrings against the lower-cased message. Deliberately narrow:
#: every one of these names the review explicitly, so ordinary conversation
#: about technical topics cannot trip it.
_TRIGGERS = (
    "technical review",
    "tech review",
    "technical architecture review",
    "architecture review",
    "start phase 2",
    "phase 2 review",
)


class HandoverError(Exception):
    """Raised when a technical review cannot be opened.

    Carries a message written for the user, not for the log, because every
    failure here is something they can act on: fix the id, finish Phase 1, or
    tell an engineer the store is not configured.
    """


def parse_tech_review_intent(user_text: str | None) -> tuple[bool, str | None]:
    """Reads a "start the technical review" request out of a chat message.

    Returns `(wants_review, record_id)`. The two are separate because
    "start the technical review" without an id is a real request that deserves
    a helpful reply, not silence — the user knows what they want and has simply
    not said which initiative.
    """
    if not user_text:
        return False, None

    text = user_text.strip()
    lowered = text.lower()

    wants = any(t in lowered for t in _TRIGGERS)
    if not wants:
        return False, None

    match = RECORD_ID_RE.search(text)
    return True, match.group(0).upper() if match else None


def start_tech_review(
    store: SessionStore, context_id: str, record_id: str
) -> Session:
    """Opens a technical review against an existing business record.

    The new session shares the record object wholesale rather than copying
    selected fields across. Phase 2 is a continuation of the same use case, so
    the initiative name, the problem statement and the sizing all stay
    authoritative and visible; the tech pack renders them readonly.

    Raises:
        HandoverError: the store cannot load records, or the id is unknown.
    """
    if not isinstance(store, RecordStore):
        raise HandoverError(
            "This deployment has no durable record store, so I can't open a "
            "record from an earlier conversation. Ask an engineer to set "
            "`QUALIFY_GCS_BUCKET` on the service."
        )

    record = store.load_record(record_id)
    if record is None:
        raise HandoverError(
            f"I can't find record **{record_id}**. Check the id — it appears "
            f"at the top of the Business Value Brief and in the SharePoint "
            f"folder name. The business intake also has to have been saved "
            f"before a technical review can start."
        )

    log.info(
        "Handover: opening tech review context_id=%s record_id=%s",
        context_id,
        record_id,
    )

    session = Session(
        context_id=context_id,
        pack_name=TECH_PACK,
        record=record,
    )
    store.save(session)
    return session


def baseline_summary(session: Session) -> str:
    """A short prose recap of what Phase 1 established.

    Shown on the handover turn so the reviewer can see immediately whether they
    have the right initiative, before answering five stages of questions about
    the wrong one.
    """
    record = session.record
    name = record.meta.initiative_name or "Unnamed initiative"
    lines = [f"**{name}** (`{record.meta.record_id}`)"]

    if record.meta.department_bu:
        lines.append(f"- Team: {record.meta.department_bu}")
    if record.business.user_count is not None:
        lines.append(f"- Affected users: {record.business.user_count}")
    if record.technical.data_sources:
        lines.append(
            f"- Systems named in Phase 1: {', '.join(record.technical.data_sources)}"
        )
    if record.technical.capability_level is not None:
        tier = record.technical.capability_level.delivery_tier
        lines.append(f"- Indicative delivery tier: {tier.label}")

    return "\n".join(lines)
